### ISSUE TITLE
The Crafter cannot output power

### ISSUE THREAD

**Issue by Chrono-Heritage** [liplum/MultiCrafterLib#15]
![image](https://user-images.githubusercontent.com/90092317/218435957-c975b036-2152-46c7-bd5d-95f0e2023703.png)
These are my Multi Crafter with power generation, as shown in the screenshot, the crafters do not output the power, it seems just store it. Is it a bug or am I just do something wrong?

**Comment by liplum** [comment]
I'm sorry for that, it's a bug that should be fixed.

**Comment by liplum** [comment]
Fixed in v1.8
