### ISSUE TITLE
multircafter can`t output power HELP FAST!!!!

### ISSUE THREAD

**Issue by PLsubfarm61** [liplum/MultiCrafterLib#16]
![Zrzut ekranu (726)](https://user-images.githubusercontent.com/122689877/224543774-50bb89d2-af8d-4011-96bd-5f7b46527c82.png)
![Zrzut ekranu (727)](https://user-images.githubusercontent.com/122689877/224543782-c60200d2-68f9-4832-a4e4-9ef2a791b741.png)
why my multicrafter can`t output power? This power is only in storage, I need fast to fix it but how? I wanted update my mod

**Comment by liplum** [comment]
Fixed in v1.8

**Comment by PLsubfarm61** [comment]
ok thx
