### ISSUE TITLE
new Jitpack release

### ISSUE THREAD

**Issue by Redmountain0** [liplum/MultiCrafterLib#25]
I need heat support so I checked IOEntry code and I found that there's heat support on github's master branch but not on jitpack release v1.7
so I suggest new jitpack release that includes latest change on github master branch

**Comment by JojoFR1** [comment]
I'm the one who made the changes, for now you could use 
`implementation "com.github.jojofr1:MultiCrafterLib:v1.7.2"`

Making an official release might not be a good idea for now due to some bugs still being around.

**Comment by liplum** [comment]
> I'm the one who made the changes, for now you could use `implementation "com.github.jojofr1:MultiCrafterLib:v1.7.2"`
> 
> Making an official release might not be a good idea for now due to some bugs still being around.

thanks, I would do it ASAP.

**Comment by JojoFR1** [comment]
The v1.8 is out, you can now use `implementation "com.github.liplum:MultiCrafterLib:1.8"`
