### ISSUE TITLE
Multicrafter refuses to input power from batteries

### ISSUE THREAD

**Issue by Delta-Airlines-ig** [liplum/MultiCrafterLib#26]
![image](https://github.com/liplum/MultiCrafterLib/assets/127794765/bbb14076-218d-4211-9724-ebfb8e79bc0d)

the crafter here should be taking power from the batteries but it isn't for some reason (they are indeed fully charged and connected). it takes power directly from generators though.
also this is using the mod as a library (separate mod not injected) in case that helps.

**Comment by JojoFR1** [comment]
It was (normally) fixed, but no release was made, some other bugs still have to be fixed

**Comment by Delta-Airlines-ig** [comment]
bruh. any way to get the fix early or should i just wait?

**Comment by liplum** [comment]
Fixed in v1.8
