### ISSUE TITLE
Same input/output stop crafter

### ISSUE THREAD

**Issue by JojoFR1** [liplum/MultiCrafterLib#27]
If a recipe that has the same items in both input and output, when the crafter is full of items, it will stop working.

How to reproduce:
1. Run `:java:runClient` gradle task.
2. Build with this schematic: 
```
bXNjaAF4nDVOQW7DIBCcYLAdRVGavqBSzxz6hp77gqoHYm8iIgwuBld9fbpgVaOdgWF3FuzRNZDeTITnj+ySfY/mmii+XPLt9Q2HkZYh2jnZ4AG0zlzILRCfXz0ONtGkl5DjQDgnm4y3edJD8Cv9hojz3axGVxq2UBzn7BYqLWO2CUdnv7Md/zOe5vBDUfswknYm3gina+AHPcdwpyFx5r7uXIMd+TcnLghVeMcQqMQi0EDsqt1sKCQ3UWj4hFZJ7lPsohePRx2UPCC3HFWkZchyazezK9KhL/IHF/I/1g==
```
3. Switch to the first recipe which has copper.

**Comment by JojoFR1** [comment]
Possible fix:

- Different item stack for input/output (Might require some UI work)
- Not allow the same input/output (Not the best solution)
- Double the item capacity but only allow X item input

**Comment by liplum** [comment]
I can reproduce it.
![image](https://github.com/liplum/MultiCrafterLib/assets/41872415/32ca6922-0d31-49f8-b59a-317080c2867f)

**Comment by JojoFR1** [comment]
> Possible fix:
> 
> - Different item stack for input/output (Might require some UI work)

Example image of how it would look:
![IMG_20231218_103703.jpg](https://github.com/liplum/MultiCrafterLib/assets/110781915/5d441e17-f39a-4d0d-9f81-07657371f196)

**Comment by JojoFR1** [comment]
Can't reproduce like the example.

Same input/output makes the block act as a big bridge/conveyor.
When the item capacity limit is reached the Efficiency is stuck (which effectively stop the crafting)
In that case, the same input/output + another output will make it impossible for the 2nd output to be produced when the same input/output reach the limit and block the craft process.

For now, I don't see any fix. Will look at it later.
Priority: Low. None or very few users will make a same input/output and it's a very specific situation.

**Comment by JojoFR1** [comment]
Closing for now. Might reopen in the future if another report comes in.
