### ISSUE TITLE
Compatibility for TooManyItems

### ISSUE THREAD

**Issue by BlueTheCube** [liplum/MultiCrafterLib#42]
where is the compatibility for [TooManyItems](https://github.com/EB-wilson/TooManyItems)

**Comment by JojoFR1** [comment]
We are not affiliated or working with TooManyItems developers. You'll have to see that with them.

**Comment by JojoFR1** [comment]
And for information, even if it is for library developers to add support. We will not. First there's no visible documentation and is not even in English and secondly it is absolutely not a priority and thirdly there's always a third.
