### ISSUE TITLE
crashes if block have 0 recipes

### ISSUE THREAD

**Issue by sheptalo** [liplum/MultiCrafterLib#6]
I created multi crafter block without recipes and when i tried to check block description game crashes with NullPointer
![2022-10-21_18-23-57](https://user-images.githubusercontent.com/104015580/197231819-819354f6-84b2-4531-b060-22a8318419c3.png)

**Comment by drfn** [comment]
yes. you really need to add at least 1 recipe to your multi crafter block (resolvedRecipes can't be null. maybe because the block calls some methods that needs the recipe as the argument(?))
